version: 2
updates:
  # Frontend code.
  - package-ecosystem: "npm"
    directory: "/kamekai"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/kamekai"
    schedule:
      interval: "weekly"

  # Backend.
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Infra.
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
