#!/bin/sh
set -euo pipefail

(
    cd kamekai/ && \
        make qa
)

(
    cd backend/ && \
        make qa
)

(
    cd infra/ && \
        terraform fmt
)

echo "scanning commit history..."
git secrets --scan-history origin/main..HEAD
