[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-sts = "1.52.0"
aws-sdk-bedrockruntime = "1.65.0"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "2.0.9"